### PR TITLE
Replace old PGP key

### PR DESCRIPTION
**Pull request by kiraio-moe**
Sir. This, it's my new PGP key.
The old one's...uh, idk why's the private key missing.
So, this is. A fresh new generated one.

### CODE REVIEW

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
No, I am not going to merge this. Because you submitted binary file here 
https://github.com/GNUWeeb/pgpkeys/blob/7ba85965248f7353588e0347c09319d8b0fb67ef/keys/AC058DD7FB403E1F5C48E5FBA09859B6599FFDF6.asc

Please use `--armor` when you export your public key.

**Comment by ammarfaizi2** [comment]
Please rebase your commits, drop the binary file commit. Add your armored public key.

**Comment by ammarfaizi2** [comment]
Export your public key with
```
gpg --armor --export AC058DD7FB403E1F5C48E5FBA09859B6599FFDF6
```

I require you to use `--armor` flag.

**Comment by kiraio-moe** [comment]
> Export your public key with
> 
> ```
> gpg --armor --export AC058DD7FB403E1F5C48E5FBA09859B6599FFDF6
> ```
> 
> I require you to use `--armor` flag.

Ah forget about that, hehe.

**Review by ammarfaizi2 — APPROVED** [review]

**Pull request merged**
