### PR TITLE
keys: Fix my key and generate the map.txt

### PR DESCRIPTION
**Pull request by Hazmi35**
Signed-off-by: Hazmi Alfarizqi <contact@hzmi.xyz>

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
Weird, when I invoke `php genmap.php`, your old UID appear again.

```
diff --git a/map.txt b/map.txt
index 97e62c7..27a5547 100644
--- a/map.txt
+++ b/map.txt
@@ -50,6 +50,12 @@ P: 42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
 U: Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>
 P: 42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
 
+U: Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>
+P: 42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
+
+U: Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>
+P: 42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
+
 U: Hendra Manudinata <manudinath@gnuweeb.org>
 P: 312964E54BB32519D9FFEB0BCB14B14B515814EF.asc
 
@@ -65,4 +71,4 @@ P: C92F25246B8C8546E6441149E8836E7712EA3305.asc
 U: mdv16h <deo@gnuweeb.org>
 P: 0CDE97A14228A94FF3331B64F15D5AA1A4865B8C.asc
 
-# Generated at: 2022-03-26T08:35:51+00:00
+# Generated at: 2022-03-26T08:47:30+00:00

```

Not sure what are you trying to fix here.

**Comment by ammarfaizi2** [comment]
Your key indeed contains the old UID.

```
ammarfaizi2@integral2:~/app/pgpkeys$ gpg keys/42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2020-02-12 [SC]
      42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE
uid           Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>
uid           Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>
uid           Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>
uid           Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>
sub   rsa4096 2020-02-12 [E]
ammarfaizi2@integral2:~/app/pgpkeys$ 
```

**Comment by ammarfaizi2** [comment]
I pulled this as-is, not sure what is going wrong :/

**Comment by Hazmi35** [comment]
> Your key indeed contains the old UID.
> 
> ```
> ammarfaizi2@integral2:~/app/pgpkeys$ gpg keys/42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE.asc
> gpg: WARNING: no command supplied.  Trying to guess what you mean ...
> pub   rsa4096 2020-02-12 [SC]
>       42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE
> uid           Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>
> uid           Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>
> uid           Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>
> uid           Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>
> sub   rsa4096 2020-02-12 [E]
> ammarfaizi2@integral2:~/app/pgpkeys$ 
> ```

Probably a problem on your side? Try deleting my key and reimporting them with the fresh one.

I've also tried generating the map on a fresh docker container with the fresh key, old UID didn't come up, also tried executing `fix.sh`, no old UID

Just my assumption, but probably because of the changes in https://github.com/GNUWeeb/pgpkeys/commit/c2c642b3b6129536f84d66946ca4742ac1782404 ?

**Comment by ammarfaizi2** [comment]
> Probably a problem on your side? Try deleting my key and reimporting them with the fresh one.

Ah yes, it's a problem from my end. My public key list contains your old UID.
```
pub   rsa4096 2020-02-12 [SC]
      42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE
uid           [ unknown] Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>
uid           [ unknown] Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>
uid           [ unknown] Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>
uid           [ unknown] Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>
sub   rsa4096 2020-02-12 [E]
```
Dropping it now...

**Comment by ammarfaizi2** [comment]
> > Probably a problem on your side? Try deleting my key and reimporting them with the fresh one.
> 
> Ah yes, it's a problem from my end. My public key list contains your old UID.
> 
> ```
> pub   rsa4096 2020-02-12 [SC]
>       42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE
> uid           [ unknown] Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>
> uid           [ unknown] Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>
> uid           [ unknown] Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>
> uid           [ unknown] Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>
> sub   rsa4096 2020-02-12 [E]
> ```
> 
> Dropping it now...

Done, pushed a fix.

**Pull request merged**
