### PR TITLE
replace the old pgp akiekano with a new one.

### PR DESCRIPTION
**Pull request by nandamade**

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
Two things need to be done:

1) Please amend your commit message to follow the commit message rules we have:
- One line title
- empty line
- Commit message
- empty line
- `Signed-off-by: Your Name <youremail@somewhere.com>`

And wrap it at 72 chars.

2) Please sign your commit with your GPG key.

Thanks!

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
As the above comment.

**Comment by nandamade** [comment]
@ammarfaizi2 I was just taught by @WalterWotah , I will do it after this.

**Comment by ammarfaizi2** [comment]
> I will do it after this.

Did you make any progress on this?

**Comment by nandamade** [comment]
> Did you make any progress on this?

Yes, im done, please review.

**Comment by nandamade** [comment]
Sorry for being late, I forgot yesterday because I was busy yesterday, I had to help my parents cook orders from customers.

わたしはごめんなさい

**Comment by ammarfaizi2** [comment]
> > Did you make any progress on this?
> 
> Yes, im done, please review.

You didn't fully address my review, there are still 2 missing parts.
1) Please wordwrap the commit message at 72 chars.
2) Please sign the commit with your GPG key.

Note:
If your commit doesn't show up as "verified" under your GPG fingerprint on GitHub, I will not merge this! Understand?

Can you please fix it, Fernanda?

**Comment by nandamade** [comment]
@ammarfaizi2 Yes forgive my mistake, I missed that part.

**Comment by ammarfaizi2** [comment]
> Sorry for being late, I forgot yesterday because I was busy yesterday, I had to help my parents cook orders from customers.
> 
> わたしはごめんなさい

No, really, don't be sorry, I'm myself quite busy, so I understand, I was just inquiring to arrange my time, nothing more.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Yes forgive my mistake, I missed that part.

OK, no rush anyway. Even early next week is okay for me.

**Comment by nandamade** [comment]
> Can you please fix it, Fernanda?

How about now? I'm a little unsure about I've finished the "And wrap it at 72 chars" part.

**Comment by ammarfaizi2** [comment]
> > Can you please fix it, Fernanda?
>
> How about now? I'm a little unsure about I've finished the "And wrap it at 72 chars" part.

No sane word-wrap of the long description. Random people's commit messages tend to be (if they have any description at all) one long unreadable line. I don't want that. So here we use 72-character columns for word-wrapping commit message, **except** for quoted material that has a specific line format.

Note:
The rule is not 80 chars, because you do want to allow the standard indentation from git log, and you do want to leave some room for quoting.

# Bad (Your current patch)
```
From 0d1af96a88f4d1d181fc69b30a50b81726318acd Mon Sep 17 00:00:00 2001
From: akiekano <hello.akiekano@gmail.com>
Date: Fri, 19 Nov 2021 07:42:59 +0700
Subject: [PATCH] replace the old pgp akiekano with a new one.

Hi, This is a follow up pull request, I am revising my previous commit message, please review this commit message, do you have any suggestions on how I can make  better commit message?

Signed-off-by: Akiekano <akiekano@gnuweeb.org>
```

# Good (Should look like this)
```
From 0d1af96a88f4d1d181fc69b30a50b81726318acd Mon Sep 17 00:00:00 2001
From: Akiekano <hello.akiekano@gmail.com>
Date: Fri, 19 Nov 2021 07:42:59 +0700
Subject: [PATCH] replace the old pgp akiekano with a new one.

Hi, This is a follow up pull request, I am revising my previous commit
message, please review this commit message, do you have any suggestions
on how I can make  better commit message?

Signed-off-by: Akiekano <hello.akiekano@gmail.com>
```

Also it seems you have configured your `user.name` wrong. The config for `user.name` should contain your name. So pay attention to the first letter for each word (see the "From" above). 

"a" in "akiekano" should be upper-case, so "Akiekano", as that's the first letter in a word.

While I am okay you're using a fake name, kernel people are not. So I still encourage to use a real name for `Signed-off-by` and commit author.

**Comment by ammarfaizi2** [comment]
Also if the author is `hello.akiekano@gmail.com`, use `hello.akiekano@gmail.com` for `Signed-off-by` as well as the GPG sign.

**Comment by ammarfaizi2** [comment]
FYI, to configure the name and email, you can just edit
```
vim ~/.gitconfig
```

**Comment by ammarfaizi2** [comment]
For editing existing commit message at HEAD, you can use this:
```
git commit --amend --author "Akiekano <hello.akiekano@gmail.com>"
```
Note:
The `--author` argument can be used to change the author, your current author is `akiekano <hello.akiekano@gmail.com>`, please use upper-case for the first letter in your name.

**Comment by nandamade** [comment]
@ammarfaizi2 error: gpg failed to sign the data
fatal: failed to write commit object


why this error always appears when i close the old terminal session 
and create with a new terminal session?

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 error: gpg failed to sign the data
> fatal: failed to write commit object
>
> why this error always appears when i close the old terminal session
> and create with a new terminal session?

It seems you didn't configure the `GPG_TTY` var correctly?
If you use bash, you can simply add
```
GPG_TTY=$(tty)
```
in your `~/.bashrc` file.

**Comment by ammarfaizi2** [comment]
Oh no, should be with `export`.
```
export GPG_TTY=$(tty)
```

**Comment by nandamade** [comment]
@ammarfaizi2 
>Oh no, should be with export. 
>export GPG_TTY=$(tty) 

Thanks.

**Comment by nandamade** [comment]
@ammarfaizi2 How about now? Am I still making mistakes?

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 How about now? Am I still making mistakes?

OK, the commit message looks good now. But the public key does not, also please update the `map.txt` file.

# Fix your public key saving format, run this:
```
./fix.sh
```

# Update the map.txt, run this
```
php genmap.php
```

After that, add and recommit (no need to the edit commit message).
```
git add -v .;
git commit --amend --no-edit;
git push --force -vvv;
```

**Comment by nandamade** [comment]
@ammarfaizi2 Done, please check.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Done, please check.

Looks good, pulled, thanks!

**Comment by nandamade** [comment]
@ammarfaizi2 So now I understand more about pgp, because yesterday just followed without experiencing try and error, thanks for some of your messages on @GNUWeeb, it really helped me, thanks for your kulgram.

良い一日を過ごしてください！！

**Pull request merged**
