### PR TITLE
feat: Rewrite genmap.php to genmap.py, add WKD hash entry

### PR DESCRIPTION
**Pull request by Hazmi35**
This commit rewrites the genmap.php to genmap.py and adds a "W" entry meaning a WKD hash entry. This commit also adds requirements.txt for pip install -r requirements.txt

The WKD hash is an SHA-1 hash with a Z-Base-32 encoded digest of the local part of an email address. This will be used to serve https://gnuweeb.org/.well-known/openpgpkey/<hash> by the server later.

The server will first read the map.txt, filter only the gnuweeb.org email address, and then serve the public keys. For automatic map.txt updates, we can use something like GitHub Actions to run the genmap.py for every change in the keys directory and then push the new map.txt to the repo. The server will also have a route for webhook where we can utilize GitHub webhook to trigger the server to add or update served public keys.

I will need your opinions on this.

REF: https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
> I will need your opinions on this.

I'm fine with this genmap script replacement. So you should continue working on this if you want to get this merged.

Now my question is, what kind of application can you offer to handle this `https://gnuweeb.org/.well-known/openpgpkey/` path? I use nginx to serve that web for now. So you need to have something that can be proxied via nginx.

**Comment by Hazmi35** [comment]
> Now my question is, what kind of application can you offer to handle this `https://gnuweeb.org/.well-known/openpgpkey/` path? I use nginx to serve that web for now. So you need to have something that can be proxied via nginx.

Yes that is the plan, I will create simple http server for that. I'm planning to use fastify and write it in typescript, thoughts?

I'll create a seperate PR for auto-generated map.txt via GitHub Actions

**Comment by ammarfaizi2** [comment]
> I will create simple http server for that. I'm planning to use fastify and write it in typescript, thoughts?

Go ahead, I want to see the minimal working HTTP app for it.

**Comment by Hazmi35** [comment]
> > I will create simple http server for that. I'm planning to use fastify and write it in typescript, thoughts?
> 
> Go ahead, I want to see the minimal working HTTP app for it.

https://github.com/GNUWeeb/pgpkeys-wkd-server Should work, but the GitHub webhook is not implemented yet, but is currently being implemented https://github.com/GNUWeeb/pgpkeys-wkd-server/pull/1

**Comment by Hazmi35** [comment]
Update: WKD Server is done, it should work after regenerating the map.txt file with the new format. For webhook you can follow the readme

**Comment by ammarfaizi2** [comment]
> Update: WKD Server is done, it should work after regenerating the map.txt file with the new format. For webhook you can follow the readme

Hi @Hazmi35,

I can't run the `pnpm start`. What seems to be the problem here?
```
root@esteh:/var/www/pgpkeys-wkd-server# pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 2.3s
root@esteh:/var/www/pgpkeys-wkd-server# 
root@esteh:/var/www/pgpkeys-wkd-server# pnpm start

> pgpkeys-wkd-server@1.0.0 start /root/server/app/www/pgpkeys-wkd-server
> node dist/index.js

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/root/server/app/www/pgpkeys-wkd-server/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.0.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Hazmi35** [comment]
> > Update: WKD Server is done, it should work after regenerating the map.txt file with the new format. For webhook you can follow the readme
> 
> Hi @Hazmi35,
> 
> I can't run the `pnpm start`. What seems to be the problem here?
> 
> ```
> root@esteh:/var/www/pgpkeys-wkd-server# pnpm install
> Lockfile is up to date, resolution step is skipped
> Already up to date
> Done in 2.3s
> root@esteh:/var/www/pgpkeys-wkd-server# 
> root@esteh:/var/www/pgpkeys-wkd-server# pnpm start
> 
> > pgpkeys-wkd-server@1.0.0 start /root/server/app/www/pgpkeys-wkd-server
> > node dist/index.js
> 
> node:internal/modules/cjs/loader:998
>   throw err;
>   ^
> 
> Error: Cannot find module '/root/server/app/www/pgpkeys-wkd-server/dist/index.js'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
>     at Module._load (node:internal/modules/cjs/loader:841:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> Node.js v19.0.0
>  ELIFECYCLE  Command failed with exit code 1.
> ```

Ah, it's typescript, have you compiled it? `pnpm run compile` first

**Comment by ammarfaizi2** [comment]
> Ah, it's typescript, have you compiled it? `pnpm run compile` first

OK, it works now after running `pnpm run compile`, despite not being found.

https://www.gnuweeb.org/.well-known/openpgpkey/hu/iyug8ridfg1hxppmuyieuft3di45cohq

**Comment by Hazmi35** [comment]
> > Ah, it's typescript, have you compiled it? `pnpm run compile` first
> 
> OK, it works now, despite not being found.
> 
> https://www.gnuweeb.org/.well-known/openpgpkey/hu/iyug8ridfg1hxppmuyieuft3di45cohq

Um, you have to merge this PR first to update the map.txt file

**Comment by ammarfaizi2** [comment]
> Um, you have to merge this PR first to update the map.txt file

Let's give it a whirl.

**Review by ammarfaizi2 — APPROVED** [review]

**Comment by Hazmi35** [comment]
Don't forget for the webhook, and #35. I also need your opinion on the automation stuff

**Comment by ammarfaizi2** [comment]
> Don't forget for the webhook, and #35. I also need your opinion on the automation stuff

I can't try it without merging, let's revoke that PR and create another branch.

**Comment by ammarfaizi2** [comment]
https://github.com/GNUWeeb/pgpkeys/tree/ci-test

The CI doesn't run. Not sure what's wrong with my setup.

**Comment by ammarfaizi2** [comment]
Oh, the push has to change the `keys/` path. I didn't realize that.

**Comment by ammarfaizi2** [comment]
The automation looks broken to me:
https://github.com/GNUWeeb/pgpkeys/commit/0de1aba381fe77e6f4798d54900905a963a4f334

I saw `[User ID]` not found and several irrelevant changes after push.

**Comment by Hazmi35** [comment]
> The automation looks broken to me: [0de1aba](https://github.com/GNUWeeb/pgpkeys/commit/0de1aba381fe77e6f4798d54900905a963a4f334)
> 
> I saw `[User ID]` not found and several irrelevant changes after push.

Nah, that's my old key broken, I need to update it, and what are the irrelevant changes?

**Comment by ammarfaizi2** [comment]
> what are the irrelevant changes?

Something like changing `expires` to `expired`. Not sure.

**Comment by ammarfaizi2** [comment]
I'll be slow to respond as I have to prepare my baggage for a flight this morning. Let's see if I have the time to work on it more tonight.

**Comment by Hazmi35** [comment]
> > what are the irrelevant changes?
> 
> Something like changing `expires` to `expired`. Not sure.

That's from `gpg -v`, what the fix job do is just run `./fix.sh`, not sure what we can do about that, but I don't think that's irrelevant?

**Comment by Hazmi35** [comment]
> I'll be slow to respond as I have to prepare my baggage for a flight this morning. Let's see if I have the time to work on it more tonight.

The WKD server is done, just the automation for map.txt regeneration, but make sure you have added the github webhooks to /internal/updateHook

**Comment by ammarfaizi2** [comment]
> The WKD server is done, just the automation for map.txt regeneration, but make sure you have added the github webhooks to /internal/updateHook

Just to clarify, I have to set a GitHub webhook to this endpoint:
https://www.gnuweeb.org/.well-known/openpgpkey/internal/updateHook

with the secret set and listen for push events. Is that correct?

**Comment by Hazmi35** [comment]
> > The WKD server is done, just the automation for map.txt regeneration, but make sure you have added the github webhooks to /internal/updateHook
> 
> Just to clarify, I have to set a GitHub webhook to this endpoint: https://www.gnuweeb.org/.well-known/openpgpkey/internal/updateHook
> 
> with the secret set and listen for push events. Is that correct?

That's correct, but it seems that the reverse proxy is giving the whole URL `/.well-known/openpgpkey/hu/dj3498u4hyyarh35rkjfnghbjxug6b19` instead of only `/hu` and `/internal`.

Will fix.

**Comment by ammarfaizi2** [comment]
> That's correct, but it seems that the reverse proxy is giving the whole URL `/.well-known/openpgpkey/hu/dj3498u4hyyarh35rkjfnghbjxug6b19` instead of only `/hu` and `/internal`.
> 
> Will fix.

Hoh, I just updated the nginx proxy to omit the `.well-known/openpgpkey`.

https://www.gnuweeb.org/.well-known/openpgpkey/internal/updateHook

Does this look ok? Should we set the whole URI like the previous state?

**Comment by Hazmi35** [comment]
> > That's correct, but it seems that the reverse proxy is giving the whole URL `/.well-known/openpgpkey/hu/dj3498u4hyyarh35rkjfnghbjxug6b19` instead of only `/hu` and `/internal`.
> > Will fix.
> 
> Hoh, I just updated the nginx proxy to omit the `.well-known/openpgpkey`.
> 
> https://www.gnuweeb.org/.well-known/openpgpkey/internal/updateHook
> 
> Does this look ok? Should we set the whole URI like the previous state?

I think it's better to use the previous state, I fixed it in the newest patch anyway

**Comment by ammarfaizi2** [comment]
As long as there is a clear agreement between the proxy and the app. Both ways are fine by me.

**Comment by ammarfaizi2** [comment]
> I think it's better to use the previous state, I fixed it in the newest patch anyway

OK.

**Comment by ammarfaizi2** [comment]
I pulled your fix and it works now, the only remaining part is the webhook. I'll set that up later.

https://www.gnuweeb.org/.well-known/openpgpkey/hu/iyug8ridfg1hxppmuyieuft3di45cohq

**Comment by Hazmi35** [comment]
> I pulled your fix and it works now, the only remaining part is the webhook. I'll set that up later.
> 
> https://www.gnuweeb.org/.well-known/openpgpkey/hu/iyug8ridfg1hxppmuyieuft3di45cohq

Yes, it's working now

image

**Comment by Hazmi35** [comment]
> > I pulled your fix and it works now, the only remaining part is the webhook. I'll set that up later.
> > https://www.gnuweeb.org/.well-known/openpgpkey/hu/iyug8ridfg1hxppmuyieuft3di45cohq
> 
> Yes, it's working now
> 
> image

It looks like gnupg dislike redirections, but well it works anyway: (Same command, with --verbose option)
```
gpg: (further info: changed from 'https://gnuweeb.org/.well-known/openpgpkey/hu/i1ay75wox3dfwuin3ekohjt33y4e68je?l=alviro.iskandar' to 'https://www.gnuweeb.org/.well-known/openpgpkey/hu/i1ay75wox3dfwuin3ekohjt33y4e68je?l=alviro.iskandar')
```

**Comment by ammarfaizi2** [comment]
> It looks like gnupg dislike redirections, but well it works anyway: (Same command, with --verbose option)

I see the problem here. The `gnuweeb.org` redirects its HTTPS request to `www.gnuweeb.org`. We can make an exception for the wdk path to not redirect it. Should be easy to get it fixed.

**Comment by Hazmi35** [comment]
> > It looks like gnupg dislike redirections, but well it works anyway: (Same command, with --verbose option)
> 
> I see the problem here. The `gnuweeb.org` redirects its HTTPS request to `www.gnuweeb.org`. We can make an exception for the wdk path to not redirect it. Should be easy to get it fixed.

BTW, what's the status for #35 ?

**Comment by ammarfaizi2** [comment]
> BTW, what's the status for #35 ?

Still in the same state, I haven't taken a look any further, I will do it today.

**Comment by ammarfaizi2** [comment]
The redirection issue has been fixed by Alviro. Thanks @alviroiskandar.

**Comment by ammarfaizi2** [comment]
> BTW, what's the status for #35 ?

From my testing, it looks OK:
```
Alt-Svc: h3=":443"; ma=86400
Cf-Cache-Status: DYNAMIC
Cf-Ray: 7e0ba0fe1b5982aa-IAD
Content-Length: 851
Content-Type: application/json; charset=utf-8
Date: Mon, 03 Jul 2023 02:16:53 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=8sqqmcnQ%2BLeRcN1zj70bWOXXDDh%2FxHyxyVRPa%2BC%2BwAS0%2F%2BEldUIBclJJnZeF6cSDBeQUQLkSFUNGtFbxGE3B2p0sFzkV0rOzNSNDHSMv3hNPO7UUnDONMKUSw%2Fp78eRLztQ%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Vary: accept-encoding

{"ok":true,"actions":[{"action":"modify","keys":[{"F":"42C1F7C64A926D4B4CF8AF7B5B41A5155041A3BE","O":{"UIDs":["Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>","Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>","Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>","Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>"],"EXP":"2025-06-02T07:24:13.000Z"},"N":{"UIDs":["Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <contact@hzmi.xyz>","Hazmi Alfarizqi (Hazmi35 / hzmi / hzmi35) <hzmi@gnuweeb.org>","Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contact@hzmi.xyz>","Hazmi35 (Just someone who likes to create useless apps. | https://hzmi.xyz/) <contacthzmi@gmail.com>"],"EXP":"2025-06-02T07:24:13.000Z"}}]}]}
```

**Comment by ammarfaizi2** [comment]
> BTW, what's the status for #35 ?

Merged via git cherry-pick. Thanks for your work. Please keep maintaining this feature.

**Pull request merged**
